site_name: '${{values.app_name}}'
site_description: 'Main documentation for ${{values.app_name}}'
repo_url: https://github.com/rubenpinzon-sketch/${{values.app_name}}
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - redirects:
      redirect_maps:
        'index.md': 'overview/what-is-backstage.md'

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting started: 'docs/index.md.md'