name: ${{values.app_name}}-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    
      - name: Declare some variables
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ vars.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}

      - name: Show image tag
        run: |
          echo "IMAGE=${{ '${{ vars.DOCKERHUB_USERNAME }}' }}/${{values.app_name}}:${{ '${{ env.COMMIT_ID }}' }}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ '${{ vars.DOCKERHUB_USERNAME }}' }}/${{values.app_name}}:${{ '${{ env.COMMIT_ID }}' }}

    outputs:
      commit_id: ${{ '${{ env.COMMIT_ID }}' }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v3
    
      - name: Set up latest Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Modify values file for tag image
        shell: bash
        run: |
          echo ${{ '${{needs.ci.outputs.commit_id}}' }}
          pip install yq
          yq -Yi '.image.tag = "${{ '${{needs.ci.outputs.commit_id}}' }}"' charts/${{values.app_name}}/values-${{values.app_env}}.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{ '${{needs.ci.outputs.commit_id}}' }}'

      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -fsSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: Ensure ArgoCD Application repo and app is Synced
        shell: bash
        run: |
          # login to argocd
          argocd login argocd-server.argocd  \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ '${{ secrets.ARGOCD_PASSWORD }}' }}
          
          # Connects the argocd repo
          repo="https://github.com/ruben-pinzon/${{values.app_name}}.git"
          argocd repo list \
          | grep -q $repo \
          || argocd repo add $repo

          # Creates the argocd app
          argocd app get ${{values.app_name}}  || argocd app create ${{values.app_name}} \
            --repo $repo \
            --path charts/${{values.app_name}} \
            --dest-namespace ${{values.app_env}} \
            --dest-server https://kubernetes.default.svc \
            --values values-${{values.app_env}}.yaml \
            --revision main \
            --sync-policy manual \
            --sync-option CreateNamespace=true

      - name: Argocd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd  \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ '${{ secrets.ARGOCD_PASSWORD }}' }}
          argocd app sync ${{values.app_name}}
          argocd app wait ${{values.app_name}} --timeout 180